# Generated by Django 5.1.7 on 2025-03-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('no_of_days', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=20)),
                ('place_to_visit', models.CharField(max_length=20)),
                ('status_parent', models.BooleanField()),
                ('status_fa', models.BooleanField()),
                ('status_incharge', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Batch_Year', models.CharField(max_length=20)),
                ('is_incharge', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.departments')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_no', models.IntegerField()),
                ('sp_id', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('FA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facultydetails')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.departments')),
            ],
        ),
        migrations.CreateModel(
            name='StudentContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=6)),
                ('Hostel_Block', models.CharField(max_length=1)),
                ('Room_No', models.CharField(max_length=3)),
                ('Parent_No', models.CharField(max_length=20)),
                ('Parent_Email', models.CharField(max_length=255)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentbasicdetails')),
            ],
        ),
    ]
