# Generated by Django 5.1.7 on 2025-03-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Batch_Year', models.CharField(max_length=20)),
                ('fp_id', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('is_incharge', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBasicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_no', models.IntegerField()),
                ('sp_id', models.IntegerField()),
                ('Batch_Year', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=20)),
                ('end_date', models.DateField(max_length=20)),
                ('no_of_days', models.IntegerField()),
                ('reason', models.CharField(max_length=20)),
                ('place_to_visit', models.CharField(max_length=20)),
                ('status_parent', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('status_fa', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('status_incharge', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentbasicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='StudentContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField()),
                ('Hostel_Block', models.CharField(max_length=1)),
                ('Room_No', models.IntegerField()),
                ('Parent_No', models.IntegerField()),
                ('Parent_Email', models.CharField(blank=True, max_length=255, null=True)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentbasicdetail')),
            ],
        ),
    ]
