# Generated by Django 5.1.7 on 2025-03-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavehistory',
            name='end_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='no_of_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='start_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcontactdetails',
            name='Parent_No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcontactdetails',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcontactdetails',
            name='Pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcontactdetails',
            name='Room_No',
            field=models.IntegerField(),
        ),
    ]
