# Generated by Django 5.1.7 on 2025-03-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_leavehistory_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='FacultyDetails',
            new_name='FacultyDetail',
        ),
        migrations.RenameModel(
            old_name='StudentBasicDetails',
            new_name='StudentBasicDetail',
        ),
        migrations.RenameModel(
            old_name='StudentContactDetails',
            new_name='StudentContactDetail',
        ),
    ]
