# Generated by Django 5.1.7 on 2025-03-27 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_departments_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavehistory',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentbasicdetail'),
        ),
        migrations.AlterField(
            model_name='studentcontactdetail',
            name='Parent_Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
